### ISSUE TITLE
[ERROR] TypeError: annotate() missing 1 required positional argument: 'text'

### ISSUE THREAD

**Issue by yemaney** [alfonsosemeraro/pyplutchik#4]
Python version: 3.8
OS: Windows, Ubuntu

Attempted: The first example from docs: https://github.com/alfonsosemeraro/pyplutchik/blob/master/Documentation.md

Error: ` [ERROR] TypeError: annotate() missing 1 required positional argument: 'text'`

What I tried:
Edited the pyplutchik script and changed `ax.annotate(s =...)` to `ax.annotate(text = ...)`

New error:
`ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead. vertices = concatenate([`

**Comment by alfonsosemeraro** [comment]
Hello, sorry for the late reply.

I fixed the **ax.annotate** bug. I also searched the ShapelyDeprecationWarning. It is an early warning introduced in shapely 1.8, about a way to extract the coordinates out of a Point/Polygon, which will be deprecated in shapely 2.0. I'm not sure I'm doing any operations that will be forbidden in version 2.0. I suspect the issue is in the definition and manipulation of a PolygonPath, or maybe in the library descartes: both are out of my hands.

I simply dismissed the warning as suggested here: https://shapely.readthedocs.io/en/latest/migration.html

I'm having troubles uploading the new release of pyplutchik on pypi; as of now, please download and use the code on Github, which is up to date. 

If you have any suggestions on how to fix the DeprecationWarning, you're welcome. 

Alfonso
